name: fixme_new
description: "A service booking app with MVVM and Firebase."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_core: ^3.12.1  # Downgraded to resolve conflict
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_database: ^11.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fixmelogo.png
    - assets/plumber-drowning-himself.jpg
    - assets/fixme-new.jpg