name: fixme_new
description: "A service booking app with MVVM and Firebase."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_core: ^3.12.1  
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_database: ^11.3.4
  logger: ^2.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fixmelogo.png
    - assets/plumber-drowning-himself.jpg
    - assets/fixme-new.jpg
    - assets/Doorbell.png
    - assets/ad.png
    - assets/plumbing_icon.png
    - assets/electrical_icon.png
    - assets/cleaning_icon.png
    - assets/mechanic_icon.png
    - assets/ac_repair_icon.png
    - assets/painter_icon.png
    - assets/meson_icon.png
    - assets/caregiver_icon.png
    - assets/home_appliance_icon.png
    - assets/more_icon.png

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.otf
    - family: Antipasto
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: londonbridgefontfamily
      fonts:
        - asset: fonts/londonbridgefontfamily.otf